//! Builtin dispatch and builtin implementations for the bytecode VM.

const Value = @import("runtime").value.Value;
const struct_census = @import("runtime").struct_census;
const builtins_mod = @import("runtime").builtins;
const BuiltinId = builtins_mod.BuiltinId;
const shared = @import("builtins/shared.zig");
const strings = @import("builtins/strings.zig");
const errors = @import("builtins/errors.zig");
const string_context = @import("builtins/string_context.zig");
const collections = @import("builtins/collections.zig");
const serial = @import("builtins/serial.zig");
const fetch = @import("builtins/fetch.zig");
const derivation_builtins = @import("builtins/derivation.zig");
const predicates = @import("builtins/predicates.zig");
const arithmetic = @import("builtins/arithmetic.zig");
const lists = @import("builtins/lists.zig");
const paths = @import("builtins/paths.zig");
const io = @import("builtins/io.zig");
const hash = @import("builtins/hash.zig");
const vm_force = @import("force.zig");
const prof = @import("../prof.zig");

pub const writeJsonValue = serial.writeJsonValue;
pub const writeLazyXmlValue = serial.writeLazyXmlValue;

pub fn applyBuiltin(self: anytype, builtin_id: u16, args: []const Value) !Value {
    const t = prof.startBuiltin(builtin_id);
    defer prof.end(.apply_builtin, t);
    const census_sp = struct_census.setProducer(struct_census.BUILTIN_BASE + builtin_id);
    defer struct_census.restoreProducer(census_sp);
    const id: BuiltinId = @enumFromInt(builtin_id);
    const arity = builtins_mod.arity(id);
    if (args.len < arity) return shared.makeBuiltinClosure(self, builtin_id, args);
    if (args.len > arity) return error.TooManyArguments;

    return switch (id) {
        .toString => strings.builtinToString(self, args[0]),
        .isAttrs => predicates.builtinTypePredicate(self, args[0], .attrs),
        .isList => predicates.builtinTypePredicate(self, args[0], .list),
        .isString => predicates.builtinIsString(self, args[0]),
        .isInt => predicates.builtinTypePredicate(self, args[0], .int),
        .isBool => predicates.builtinIsBool(self, args[0]),
        .isNull => predicates.builtinTypePredicate(self, args[0], .null),
        .isFloat => predicates.builtinTypePredicate(self, args[0], .float),
        .isFunction => predicates.builtinIsFunction(self, args[0]),
        .isPath => predicates.builtinTypePredicate(self, args[0], .path),
        .length => lists.builtinLength(self, args[0]),
        .head => lists.builtinHead(self, args[0]),
        .tail => lists.builtinTail(self, args[0]),
        .attrNames => collections.builtinAttrNames(self, args[0]),
        .attrValues => collections.builtinAttrValues(self, args[0]),
        .typeOf => predicates.builtinTypeOf(self, args[0]),
        .concatLists => lists.builtinConcatLists(self, args[0]),
        .listToAttrs => lists.builtinListToAttrs(self, args[0]),
        .pathExists => io.builtinPathExists(self, args[0]),
        .readFile => io.builtinReadFile(self, args[0]),
        .import => io.builtinImport(self, args[0]),
        .readDir => io.builtinReadDir(self, args[0]),
        .readFileType => io.builtinReadFileType(self, args[0]),
        .findFile => io.builtinFindFile(self, args[0], args[1]),
        .hasAttr => collections.builtinHasAttr(self, args[0], args[1]),
        .getAttr => collections.builtinGetAttr(self, args[0], args[1]),
        .elemAt => collections.builtinElemAt(self, args[0], args[1]),
        .removeAttrs => collections.builtinRemoveAttrs(self, args[0], args[1]),
        .intersectAttrs => collections.builtinIntersectAttrs(self, args[0], args[1]),
        .elem => collections.builtinElem(self, args[0], args[1]),
        .seq => collections.builtinSeq(self, args[0], args[1]),
        .all => collections.builtinAll(self, args[0], args[1]),
        .any => collections.builtinAny(self, args[0], args[1]),
        .filter => collections.builtinFilter(self, args[0], args[1]),
        .map => collections.builtinMap(self, args[0], args[1]),
        .concatMap => collections.builtinConcatMap(self, args[0], args[1]),
        .mapAttrs => collections.builtinMapAttrs(self, args[0], args[1]),
        .genList => collections.builtinGenList(self, args[0], args[1]),
        .stringLength => strings.builtinStringLength(self, args[0]),
        .concatStringsSep => strings.builtinConcatStringsSep(self, args[0], args[1]),
        .foldlStrict => collections.builtinFoldlStrict(self, args[0], args[1], args[2]),
        .substring => strings.builtinSubstring(self, args[0], args[1], args[2]),
        .replaceStrings => strings.builtinReplaceStrings(self, args[0], args[1], args[2]),
        .deepSeq => collections.builtinDeepSeq(self, args[0], args[1]),
        .throw => errors.builtinThrow(self, args[0]),
        .abort => errors.builtinAbort(self, args[0]),
        .tryEval => errors.builtinTryEval(self, args[0]),
        .trace => errors.builtinTrace(self, args[0], args[1]),
        .derivation => derivation_builtins.builtinDerivation(self, args[0], .lazy),
        .derivationStrict => derivation_builtins.builtinDerivation(self, args[0], .strict),
        .storePath => paths.builtinStorePath(self, args[0]),
        .path => paths.builtinPath(self, args[0]),
        .sort => collections.builtinSort(self, args[0], args[1]),
        .partition => collections.builtinPartition(self, args[0], args[1]),
        .groupBy => collections.builtinGroupBy(self, args[0], args[1]),
        .genericClosure => collections.builtinGenericClosure(self, args[0]),
        .functionArgs => collections.builtinFunctionArgs(self, args[0]),
        .unsafeGetAttrPos => collections.builtinUnsafeGetAttrPos(self, args[0], args[1]),
        .add => arithmetic.builtinAdd(self, args[0], args[1]),
        .sub => arithmetic.builtinSub(self, args[0], args[1]),
        .mul => arithmetic.builtinMul(self, args[0], args[1]),
        .div => arithmetic.builtinDiv(self, args[0], args[1]),
        .lessThan => arithmetic.builtinLessThan(self, args[0], args[1]),
        .bitAnd => arithmetic.builtinBitAnd(self, args[0], args[1]),
        .bitOr => arithmetic.builtinBitOr(self, args[0], args[1]),
        .bitXor => arithmetic.builtinBitXor(self, args[0], args[1]),
        .floor => arithmetic.builtinFloor(self, args[0]),
        .ceil => arithmetic.builtinCeil(self, args[0]),
        .baseNameOf => paths.builtinBaseNameOf(self, args[0]),
        .dirOf => paths.builtinDirOf(self, args[0]),
        .catAttrs => collections.builtinCatAttrs(self, args[0], args[1]),
        .zipAttrsWith => collections.builtinZipAttrsWith(self, args[0], args[1]),
        .hashString => hash.builtinHashString(self, args[0], args[1]),
        .hashFile => hash.builtinHashFile(self, args[0], args[1]),
        .mapAttrValue => collections.builtinMapAttrValue(self, args[0], args[1], args[2]),
        .zipAttrsValue => collections.builtinZipAttrsValue(self, args[0], args[1], args[2]),
        .toJSON => serial.builtinToJSON(self, args[0]),
        .fromJSON => serial.builtinFromJSON(self, args[0]),
        .toXML => serial.builtinToXML(self, args[0]),
        .compareVersions => serial.builtinCompareVersions(self, args[0], args[1]),
        .splitVersion => serial.builtinSplitVersion(self, args[0]),
        .parseDrvName => serial.builtinParseDrvName(self, args[0]),
        .getEnv => fetch.builtinGetEnv(self, args[0]),
        .match => serial.builtinMatch(self, args[0], args[1]),
        .split => serial.builtinSplit(self, args[0], args[1]),
        .fromTOML => serial.builtinFromTOML(self, args[0]),
        .filterSource => fetch.builtinFilterSource(self, args[0], args[1]),
        .fetchGit => fetch.builtinFetchGit(self, args[0]),
        .fetchurl => fetch.builtinFetchurl(self, args[0]),
        .fetchTarball => fetch.builtinFetchTarball(self, args[0]),
        .fetchTree => fetch.builtinFetchTree(self, args[0]),
        .parseFlakeRef => fetch.builtinParseFlakeRef(self, args[0]),
        .flakeRefToString => fetch.builtinFlakeRefToString(self, args[0]),
        .fetchMercurial => fetch.builtinFetchMercurial(self, args[0]),
        .getFlake => fetch.builtinGetFlake(self, args[0]),
        .scopedImport => io.builtinScopedImport(self, args[0], args[1]),
        .traceVerbose => errors.builtinTraceVerbose(self, args[0], args[1]),
        .addErrorContext => errors.builtinAddErrorContext(self, args[0], args[1]),
        .unsafeDiscardStringContext => string_context.builtinUnsafeDiscardStringContext(self, args[0]),
        .unsafeDiscardOutputDependency => string_context.builtinUnsafeDiscardOutputDependency(self, args[0]),
        .addDrvOutputDependencies => string_context.builtinAddDrvOutputDependencies(self, args[0]),
        .appendContext => string_context.builtinAppendContext(self, args[0], args[1]),
        .break_ => vm_force.forceValue(self, args[0]),
        .getContext => string_context.builtinGetContext(self, args[0]),
        .hasContext => string_context.builtinHasContext(self, args[0]),
        .toPath => fetch.builtinToPath(self, args[0]),
        .toFile => fetch.builtinToFile(self, args[0], args[1]),
        .placeholder => paths.builtinPlaceholder(self, args[0]),
        .derivationLazyAttr => derivation_builtins.builtinDerivationLazyAttr(self, args[0], args[1]),
        .mapValue => collections.builtinMapValue(self, args[0], args[1]),
        .constantValue => args[0],
    };
}
