//! Codegen tool: build the LALR(1) parser tables from the grammar and emit them
//! as a plain `.zig` of literal arrays. Wired into `build.zig` as a run step
//! whose single argument is the output path.
//!
//! The point is caching: `lr.Generate` is expensive at comptime, so paying it
//! here — in a standalone artifact the build system caches and only rebuilds
//! when the grammar or generator changes — keeps it off the hot path of every
//! ordinary `syntax`-module rebuild. The emitted file compiles instantly.

const std = @import("std");
const lr = @import("lr.zig");
const grammar = @import("grammar.zig");

// The one expensive comptime evaluation, isolated to this tool.
const Tab = lr.Generate(grammar.desc);

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    var args = try init.minimal.args.iterateAllocator(init.gpa);
    defer args.deinit();
    _ = args.next(); // program name
    const out_path = args.next() orelse return error.MissingOutputPath;

    const file = try std.Io.Dir.cwd().createFile(io, out_path, .{});
    defer file.close(io);
    var buf: [1 << 16]u8 = undefined;
    var fw = file.writerStreaming(io, &buf);
    const w = &fw.interface;

    try w.writeAll(
        \\//! GENERATED by tools/gen_parser_tables.zig — do not edit.
        \\//! LALR(1) ACTION/GOTO tables for the Nix grammar (see grammar.zig).
        \\
        \\
    );
    try w.print("pub const num_states: u32 = {d};\n", .{Tab.num_states});
    try w.print("pub const num_terminals: u32 = {d};\n", .{Tab.num_terminals});
    try w.print("pub const num_nonterminals: u32 = {d};\n", .{Tab.num_nonterminals});
    try w.print("pub const num_productions: u32 = {d};\n", .{Tab.num_productions});
    try w.print("pub const start_state: u32 = {d};\n", .{Tab.start_state});
    try w.print("pub const eof: u32 = {d};\n\n", .{Tab.eof});
    try emit(w, lr.Cell, "action", Tab.action);
    try emit(w, i16, "goto_table", Tab.goto_table);
    try emit(w, u32, "prod_lhs", Tab.prod_lhs);
    try emit(w, u32, "prod_rhs_len", Tab.prod_rhs_len);
    try w.flush();
}

fn emit(w: *std.Io.Writer, comptime T: type, name: []const u8, arr: []const T) !void {
    try w.print("pub const {s} = [_]{s}{{", .{ name, @typeName(T) });
    for (arr, 0..) |x, i| {
        if (i % 24 == 0) try w.writeAll("\n    ");
        try w.print("{d},", .{x});
    }
    try w.writeAll("\n};\n\n");
}
