//! Codegen tool: build the LALR(1) parser tables from the grammar and emit them
//! as a plain `.zig` of literal arrays. Wired into `build.zig` as a run step
//! whose single argument is the output path.
//!
//! The point is caching AND avoiding comptime: `lr.generate` builds the tables
//! with ordinary native loops when this tool runs during the build, then emits
//! them as static array literals. The build system caches the artifact and only
//! reruns it when the grammar or generator changes, keeping the cost off every
//! ordinary `syntax`-module rebuild. The emitted file compiles instantly, and
//! the shipped `fix` binary contains only these baked-in static arrays — it does
//! no table construction at eval time.

const std = @import("std");
const lr = @import("lr.zig");
const grammar = @import("grammar.zig");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    var args = try init.minimal.args.iterateAllocator(init.gpa);
    defer args.deinit();
    _ = args.next(); // program name
    const out_path = args.next() orelse return error.MissingOutputPath;

    // Build the tables natively into an arena (freed on exit).
    var arena = std.heap.ArenaAllocator.init(init.gpa);
    defer arena.deinit();
    const tab = try lr.generate(arena.allocator(), grammar.desc);

    const file = try std.Io.Dir.cwd().createFile(io, out_path, .{});
    defer file.close(io);
    var buf: [1 << 16]u8 = undefined;
    var fw = file.writerStreaming(io, &buf);
    const w = &fw.interface;

    try w.writeAll(
        \\//! GENERATED by tools/gen_parser_tables.zig — do not edit.
        \\//! LALR(1) ACTION/GOTO tables for the Nix grammar (see grammar.zig).
        \\
        \\
    );
    try w.print("pub const num_states: u32 = {d};\n", .{tab.num_states});
    try w.print("pub const num_terminals: u32 = {d};\n", .{tab.num_terminals});
    try w.print("pub const num_nonterminals: u32 = {d};\n", .{tab.num_nonterminals});
    try w.print("pub const num_productions: u32 = {d};\n", .{tab.num_productions});
    try w.print("pub const start_state: u32 = {d};\n", .{tab.start_state});
    try w.print("pub const eof: u32 = {d};\n\n", .{tab.eof});
    try emit(w, lr.Cell, "action", tab.action);
    try emit(w, i16, "goto_table", tab.goto_table);
    try emit(w, u32, "prod_lhs", tab.prod_lhs);
    try emit(w, u32, "prod_rhs_len", tab.prod_rhs_len);
    try w.flush();
}

fn emit(w: *std.Io.Writer, comptime T: type, name: []const u8, arr: []const T) !void {
    try w.print("pub const {s} = [_]{s}{{", .{ name, @typeName(T) });
    for (arr, 0..) |x, i| {
        if (i % 24 == 0) try w.writeAll("\n    ");
        try w.print("{d},", .{x});
    }
    try w.writeAll("\n};\n\n");
}
