//! Evaluator-owned builtin values.

const std = @import("std");
const builtin = @import("builtin");
const InternTable = @import("intern.zig").InternTable;
const heap_mod = @import("heap.zig");
const ObjectHeap = heap_mod.ObjectHeap;
const AttrEntry = heap_mod.AttrEntry;
const Value = @import("value.zig").Value;

pub const BuiltinId = enum(u16) {
    toString = 0,
    isAttrs = 1,
    isList = 2,
    isString = 3,
    isInt = 4,
    isBool = 5,
    isNull = 6,
    isFloat = 7,
    isFunction = 8,
    isPath = 9,
    length = 10,
    head = 11,
    tail = 12,
    attrNames = 13,
    attrValues = 14,
    hasAttr = 15,
    getAttr = 16,
    elemAt = 17,
    typeOf = 18,
    concatLists = 19,
    listToAttrs = 20,
    removeAttrs = 21,
    intersectAttrs = 22,
    elem = 23,
    seq = 24,
    all = 25,
    any = 26,
    filter = 27,
    foldlStrict = 28,
    deepSeq = 29,
    pathExists = 30,
    readFile = 31,
    import = 32,
    readDir = 33,
    readFileType = 34,
    findFile = 35,
    map = 36,
    concatMap = 37,
    mapAttrs = 38,
    genList = 39,
    stringLength = 40,
    concatStringsSep = 41,
    substring = 42,
    replaceStrings = 43,
    throw = 44,
    abort = 45,
    tryEval = 46,
    trace = 47,
    derivation = 48,
    derivationStrict = 49,
    storePath = 50,
    path = 51,
    sort = 52,
    partition = 53,
    groupBy = 54,
    genericClosure = 55,
    functionArgs = 56,
    unsafeGetAttrPos = 57,
    add = 58,
    sub = 59,
    mul = 60,
    div = 61,
    lessThan = 62,
    bitAnd = 63,
    bitOr = 64,
    bitXor = 65,
    floor = 66,
    ceil = 67,
    baseNameOf = 68,
    dirOf = 69,
    catAttrs = 70,
    zipAttrsWith = 71,
    hashString = 72,
    hashFile = 73,
    mapAttrValue = 74,
    zipAttrsValue = 75,
    toJSON = 76,
    fromJSON = 77,
    compareVersions = 78,
    splitVersion = 79,
    parseDrvName = 80,
};

const BuiltinBinding = struct {
    name: []const u8,
    id: BuiltinId,
};

const builtin_bindings = [_]BuiltinBinding{
    .{ .name = "toString", .id = .toString },
    .{ .name = "isAttrs", .id = .isAttrs },
    .{ .name = "isList", .id = .isList },
    .{ .name = "isString", .id = .isString },
    .{ .name = "isInt", .id = .isInt },
    .{ .name = "isBool", .id = .isBool },
    .{ .name = "isNull", .id = .isNull },
    .{ .name = "isFloat", .id = .isFloat },
    .{ .name = "isFunction", .id = .isFunction },
    .{ .name = "isPath", .id = .isPath },
    .{ .name = "length", .id = .length },
    .{ .name = "head", .id = .head },
    .{ .name = "tail", .id = .tail },
    .{ .name = "attrNames", .id = .attrNames },
    .{ .name = "attrValues", .id = .attrValues },
    .{ .name = "hasAttr", .id = .hasAttr },
    .{ .name = "getAttr", .id = .getAttr },
    .{ .name = "elemAt", .id = .elemAt },
    .{ .name = "typeOf", .id = .typeOf },
    .{ .name = "concatLists", .id = .concatLists },
    .{ .name = "listToAttrs", .id = .listToAttrs },
    .{ .name = "removeAttrs", .id = .removeAttrs },
    .{ .name = "intersectAttrs", .id = .intersectAttrs },
    .{ .name = "elem", .id = .elem },
    .{ .name = "seq", .id = .seq },
    .{ .name = "all", .id = .all },
    .{ .name = "any", .id = .any },
    .{ .name = "filter", .id = .filter },
    .{ .name = "foldl'", .id = .foldlStrict },
    .{ .name = "deepSeq", .id = .deepSeq },
    .{ .name = "pathExists", .id = .pathExists },
    .{ .name = "readFile", .id = .readFile },
    .{ .name = "import", .id = .import },
    .{ .name = "readDir", .id = .readDir },
    .{ .name = "readFileType", .id = .readFileType },
    .{ .name = "findFile", .id = .findFile },
    .{ .name = "map", .id = .map },
    .{ .name = "concatMap", .id = .concatMap },
    .{ .name = "mapAttrs", .id = .mapAttrs },
    .{ .name = "genList", .id = .genList },
    .{ .name = "stringLength", .id = .stringLength },
    .{ .name = "concatStringsSep", .id = .concatStringsSep },
    .{ .name = "substring", .id = .substring },
    .{ .name = "replaceStrings", .id = .replaceStrings },
    .{ .name = "throw", .id = .throw },
    .{ .name = "abort", .id = .abort },
    .{ .name = "tryEval", .id = .tryEval },
    .{ .name = "trace", .id = .trace },
    .{ .name = "derivation", .id = .derivation },
    .{ .name = "derivationStrict", .id = .derivationStrict },
    .{ .name = "storePath", .id = .storePath },
    .{ .name = "path", .id = .path },
    .{ .name = "sort", .id = .sort },
    .{ .name = "partition", .id = .partition },
    .{ .name = "groupBy", .id = .groupBy },
    .{ .name = "genericClosure", .id = .genericClosure },
    .{ .name = "functionArgs", .id = .functionArgs },
    .{ .name = "unsafeGetAttrPos", .id = .unsafeGetAttrPos },
    .{ .name = "add", .id = .add },
    .{ .name = "sub", .id = .sub },
    .{ .name = "mul", .id = .mul },
    .{ .name = "div", .id = .div },
    .{ .name = "lessThan", .id = .lessThan },
    .{ .name = "bitAnd", .id = .bitAnd },
    .{ .name = "bitOr", .id = .bitOr },
    .{ .name = "bitXor", .id = .bitXor },
    .{ .name = "floor", .id = .floor },
    .{ .name = "ceil", .id = .ceil },
    .{ .name = "baseNameOf", .id = .baseNameOf },
    .{ .name = "dirOf", .id = .dirOf },
    .{ .name = "catAttrs", .id = .catAttrs },
    .{ .name = "zipAttrsWith", .id = .zipAttrsWith },
    .{ .name = "hashString", .id = .hashString },
    .{ .name = "hashFile", .id = .hashFile },
    .{ .name = "toJSON", .id = .toJSON },
    .{ .name = "fromJSON", .id = .fromJSON },
    .{ .name = "compareVersions", .id = .compareVersions },
    .{ .name = "splitVersion", .id = .splitVersion },
    .{ .name = "parseDrvName", .id = .parseDrvName },
};

pub fn arity(id: BuiltinId) u8 {
    return switch (id) {
        .toString,
        .isAttrs,
        .isList,
        .isString,
        .isInt,
        .isBool,
        .isNull,
        .isFloat,
        .isFunction,
        .isPath,
        .length,
        .head,
        .tail,
        .attrNames,
        .attrValues,
        .typeOf,
        .concatLists,
        .listToAttrs,
        .pathExists,
        .readFile,
        .import,
        .readDir,
        .readFileType,
        .stringLength,
        .throw,
        .abort,
        .tryEval,
        .derivation,
        .derivationStrict,
        .storePath,
        .path,
        .genericClosure,
        .functionArgs,
        .toJSON,
        .fromJSON,
        .splitVersion,
        .parseDrvName,
        .floor,
        .ceil,
        .baseNameOf,
        .dirOf,
        => 1,
        .hasAttr,
        .getAttr,
        .elemAt,
        .removeAttrs,
        .intersectAttrs,
        .elem,
        .seq,
        .all,
        .any,
        .filter,
        .deepSeq,
        .findFile,
        .map,
        .concatMap,
        .mapAttrs,
        .genList,
        .concatStringsSep,
        .trace,
        .sort,
        .partition,
        .groupBy,
        .unsafeGetAttrPos,
        .add,
        .sub,
        .mul,
        .div,
        .lessThan,
        .bitAnd,
        .bitOr,
        .bitXor,
        .catAttrs,
        .zipAttrsWith,
        .hashString,
        .hashFile,
        .compareVersions,
        => 2,
        .foldlStrict,
        .substring,
        .replaceStrings,
        .mapAttrValue,
        .zipAttrsValue,
        => 3,
    };
}

pub fn buildAttrSet(intern: *InternTable, heap: *ObjectHeap) !Value {
    const constant_count = 6;
    var entries: [builtin_bindings.len + constant_count]AttrEntry = undefined;
    var i: usize = 0;

    for (builtin_bindings) |binding| {
        entries[i] = try builtinEntry(intern, binding);
        i += 1;
    }

    entries[i] = .{ .name = try intern.intern("true"), .value = Value.boolVal(true) };
    i += 1;
    entries[i] = .{ .name = try intern.intern("false"), .value = Value.boolVal(false) };
    i += 1;
    entries[i] = .{ .name = try intern.intern("null"), .value = Value.null_val };
    i += 1;
    entries[i] = .{ .name = try intern.intern("langVersion"), .value = Value.int(6) };
    i += 1;
    entries[i] = .{
        .name = try intern.intern("storeDir"),
        .value = Value.string(try intern.intern("/nix/store")),
    };
    i += 1;
    entries[i] = .{
        .name = try intern.intern("currentSystem"),
        .value = Value.string(try intern.intern(hostSystemName())),
    };
    i += 1;

    std.debug.assert(i == entries.len);
    return Value.attrs(try heap.addAttrs(&entries));
}

fn builtinEntry(intern: *InternTable, binding: BuiltinBinding) !AttrEntry {
    return .{
        .name = try intern.intern(binding.name),
        .value = Value.builtin(@intFromEnum(binding.id)),
    };
}

fn hostSystemName() []const u8 {
    return switch (builtin.target.os.tag) {
        .linux => switch (builtin.target.cpu.arch) {
            .x86_64 => "x86_64-linux",
            .aarch64 => "aarch64-linux",
            .arm => "armv7l-linux",
            .riscv64 => "riscv64-linux",
            else => "unknown-linux",
        },
        .macos => switch (builtin.target.cpu.arch) {
            .x86_64 => "x86_64-darwin",
            .aarch64 => "aarch64-darwin",
            else => "unknown-darwin",
        },
        .freebsd => switch (builtin.target.cpu.arch) {
            .x86_64 => "x86_64-freebsd",
            .aarch64 => "aarch64-freebsd",
            else => "unknown-freebsd",
        },
        else => "unknown",
    };
}
